---
title: "2.4 OLS: Precision and Diagnostics - R Practice (Answers)"
editor_options: 
  chunk_output_type: console
---

```{r message=FALSE, warning=FALSE, include=FALSE}
library(tidyverse)
library(pander)
source(file.path(here::here(), "lib", "graphics.R"))
```

Our [data](https://github.com/fivethirtyeight/data/tree/master/congress-trump-score) comes from fivethirtyeight's [Trump Congress tracker](https://projects.fivethirtyeight.com/congress-trump-score/).

- [View Project on R Studio Cloud](https://rstudio.cloud/project/575252)

## Question 1
Download and read in (`read_csv`) the data.

## Question 2
Look at the data with `glimpse()`. 

## Question 3
We want to see *how does the percentage that a member of Congress' agrees with President Trump (`agree_pct`) depend on the result of the 2016 Presidential election in their district (`net_trump_vote`)*? First, plot a scatterplot of `agree_pct` on `net_trump_vote`. Add a regression line with an additional layer of `geom_smooth(method="lm")`.

## Question 4
Find the correlation between `agree_pct` and `net_trump_vote`.

## Question 5
We weant to predict the following model:

$$\widehat{\text{agree_pct}}= \hat{\beta_0}+\hat{\beta_1}\text{net_trump_vote}$$

Run a regression, and save it as an object. Now get a `summary()` of it.

### Part A
What is $\hat{\beta_0}$? What does it mean in the context of our question?

### Part B
What is $\hat{\beta_1}$? What does it mean in the context of our question?

### Part C
What is $R^2$? What does it mean?

### Part D
What is the $SER$? What does it mean?

## Question 6
We can look at regression outputs in a tidier way, with the `broom` package. 

### Part A
Install and then load `broom`.

### Part B
Run the function `tidy()` on your regression object (saved in question 5). Save this as an object and then look at it.

### Part C
Run the `glance()` function on your original regression object. What does it show you?

### Part D
Now run the `augment()` function on your original regression object, and save this as an object. Look at it. What does it show you?

## Question 7
Now let's start looking at the residuals of the regression. 

### Part A
Take the augmented regression object from Question 6-D and use it as the source of your data to create a histogram, where $x$ is `.resid`. Does it look roughly normal?

### Part B
Take the augmented regression object and make a residual plot, which is a scatterplot where `x` is the normal `x` variable, and `y` is the `.resid`. Feel free to add a horizontal line at 0 with `geom_hline(yintercept=0)`. 

## Question 8
Now let's try presenting your results in a regression table. Install and load `huxtable`, and run the `huxreg()` command. Your main input is your regression object you saved in Question 5. Feel free to customize the output of this table (see the slides).

## Question 9
Now let's check for heteroskedasticity. 

### Part A
Looking at the scatterplot and residual plots in Questions 3 and 7B, do you think the errors are heteroskedastic or homoskedastic?

### Part B
Install and load the `lmtest` package and run `bptest` on your regression object. Was the data heteroskedastic or homoskedastic?

### Part C
Now let's make some heteroskedasticity-robust standard errors. Install and load the `estimatr` package and use the `lm_robust()` command (instead of the `lm()` command) to run a new regression (and save it). Make sure you add `se_type="stata"` inside the command to calculate robust SEs. Look at it. What changes?

### Part D
Now let's see this in a nice regression table. Use `huxreg()` again, but add both your original regression and your regression saved in part C. Notice any changes?

## Question 10
Now let's check for outliers. 

### Part A
Just looking at the scatterplot in Question 3, do you see any outliers?

### Part B
Install and load the `car` package. Run the `outlierTest` command on your regression object. Does it detect any outliers?

### Part C
Look in your original data to match this outlier with an observation. Hint: use the `slice()` command, as the outlier test gave you an observation number!

## Question 11 (Optional)

This data is still a bit messy. We'd also probably like to plot our scatterplots with colors for Republican and Democratic party. Or sort by the House and the Senate.