---
title: "1.6: Optimize Your Workflow: Projects, Markdown, and Git - Class Notes"
citeproc: false
bibliography: ../../static/bib/references.bib
csl: ../../static/bib/chicago-syllabus-no-bib.csl
output:
  blogdown::html_page:
    template: ../../pandoc/toc-title_html.template
    toc: true
editor_options: 
  chunk_output_type: console
---

*Tuesday, September 10, 2019*

# Overview

Today I will give you about half the class period to finish your practice problems and I can answer questions.   

# Knitting on Trading Room Computers

Last year, IT and I were unable to get the Trading Room computers to knit to pdf. I may have a workaround. We will install a minimal version of $\LaTeX{}$ inside of R Studio. Run the following code:

```{r, eval=F}
tinytex::install_tinytex()
```

Then make a new `.Rmd` and try to `knit` it to `pdf`. It may install several packages (`knitr` and `rmarkdown` at least) and ask you a few prompts. It should then work. 

# Slides

- [<i class="fas fa-external-link-square-alt"></i> Lecture Slides](/slides/06-slides.html)

# Practice Problems

The answer keys (in various formats) to last class's practice problems (on data wrangling in the `tidyverse`) have been [posted](/r/05-r-practice.html). Today's "[practice problems](/r/06-r-practice.html)" are a series of raw `.Rmd` files that I've used for various things, so you can see how they work.

# Problem Set

[Problem Set 1](/assignment/01-problem-set.html) is posted and is due Thursday September 19. 

# Additional Useful Information

See the last 2 slides and the readings page for my workflow, my suggestions to you, and a series of links to more resources and readings.